obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: 1.0
footprint: [ [0.5, 0.25], [0.5, -0.25], [-0.2, -0.25], [-0.2, 0.25] ]
inflation_radius: 0.5
max_obstacle_height: 0.6
min_obstacle_height: 0.0
#observation_sources: scan
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}


